### ISSUE TITLE
About PICA

### ISSUE THREAD

**Issue by SodiumAzide** [ReChinX/Meow#1]
不知道开发者你能不能成功登陆。我抓到secret Key后，写爬虫就没成功过，ahhh。刚刚用你的app也是没法登陆。
I don't know whether you could login using that secret key.I have never succeeded since I hooked that key.But I have tried your app without success just now.

**Comment by ReChinX** [comment]
ahhh看了你的repo发现了你也在做pica的抓包，握爪，我也是从你的repo里找到灵感才做出来的，thanks

**Comment by SodiumAzide** [comment]
我一直返回请求次数过多，但是客户端又能正常登陆，伪造的报文也没问题，也可以排除ip被拉黑名单。不知道哪弄错了。。。。。
弄这个也是被一个XX开发者气的，看他很不爽，就hook了pica，然后就开源他的key出来。

**Comment by SodiumAzide** [comment]
你使用的本地二级代理是哪个开源项目，还是自己搭建的？

**Comment by ReChinX** [comment]
ss呀，ss的代理端口就是这个

**Comment by SodiumAzide** [comment]
原来如此，ahhhh

**Comment by ReChinX** [comment]
经过测试，问题出现在登录接口处没有外接pica的dns，所以只有在翻墙的情况下才能进行登录pica的操作。
可以认为issue可以关闭了吧qaq
